package kamil.rojek.ox.inputOutput;

public enum LocalizationKey {
    //MAIN MENU
    MENU_INFO, START_GAME, OPTIONS, QUIT,
    CHANGE_BOARD_SIZE, CHANGE_WINNING_LIMIT, CHANGE_NUMBER_ROUNDS,
    CHANGE_LANGUAGE, GO_MAIN_MENU, SET_ROW_SIZE_INFO, SET_COLUMN_SIZE_INFO,
    SET_WINNING_LIMIT_INFO, SET_NUMBER_OF_ROUNDS_INFO,
    GAME_ENDED_INFO, POLISH_LANGUAGE, ENGLISH_LANGUAGE, GO_SETTINGS,

    //SETTINGS
    BOARD_SIZE_WARNING, WINNING_LIMIT_WARNING, NUMBER_OF_ROUNDS_WARNING,

    //GAME
    ROUND_ENDED_WINNER, ROUND_ENDED_DRAW, TURN_MOVE,
    MOVE_PLAYER_ROW_TYPE, MOVE_PLAYER_COLUMN_TYPE,

    //TABLICA WYNIKÓW
    SCORE_BOARD_START, SCORE_BOARD_END, ADDIDNG_POINT,

    //INPUT
    INTEGER_INPUT_WARNING

}
